version: '3'

services:
  db:
    image: postgres:16
    env_file:
      - deb.env
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier
      - result-tier
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: always

  worker:
    build:
      context: ./worker
    env_file:
      - deb.env
      - poll.env
      - result.env
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    restart: always

  poll:
    build:
      context: ./poll
    env_file:
      - poll.env
    ports:
      - "5000:80"
    networks:
      - poll-tier
    depends_on:
      - redis
    restart: always

  result:
    build:
      context: ./result
    env_file:
      - result.env
      - deb.env
    ports:
      - "5001:80"
    networks:
      - result-tier
    depends_on:
      - db
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: