version: '3'

services:
  db:
    image: postgres:16
    env_file:
      - deb.env
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier
      - result-tier
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - redis.env
    networks:
      - poll-tier
      - back-tier
      - graph
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '5540:5540'
    volumes:
      - ./graphdata:/db
    networks:
      - graph
    restart: always

  poll:
    build:
      context: ./poll
    env_file:
      - poll.env
      - redis.env
    ports:
      - "5000:80"
    networks:
      - poll-tier
    depends_on:
      - redis
    restart: always

  result:
    build:
      context: ./result
    env_file:
      - result.env
      - deb.env
    ports:
      - "5001:80"
    networks:
      - result-tier
    depends_on:
      - db
    restart: always

  worker:
    build:
      context: ./worker
    env_file:
      - deb.env
      - poll.env
      - redis.env
      - result.env
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:
  graph:

volumes:
  db-data: